In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv('http://files.grouplens.org/datasets/movielens/ml-100k/u.data')
df

196\t242\t3\t881250949
0       186\t302\t3\t891717742
1        22\t377\t1\t878887116
2        244\t51\t2\t880606923
3       166\t346\t1\t886397596
4       298\t474\t4\t884182806
...                        ...
99994   880\t476\t3\t880175444
99995   716\t204\t5\t879795543
99996  276\t1090\t1\t874795795
99997    13\t225\t2\t882399156
99998    12\t203\t3\t879959583

[99999 rows x 1 columns]

In [3]:
df = pd.read_csv(
    'http://files.grouplens.org/datasets/movielens/ml-100k/u.data', 
    names=["user_id", 
           "item_id", 
           "review", 
           "timestamp"], 
    sep="\t"
)
df

user_id  item_id  review  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

In [4]:
df1 = pd.pivot_table(df.drop("timestamp", axis=1), index="user_id", columns="item_id", values="review")
df1

item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5         4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   
940       NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   
941       5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
943       NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   

item_id  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
user_id                                                              
1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[943 rows x 1682 columns]

In [5]:
df2 = df1.fillna(0)

In [6]:
#array[0][0] ⇒ 行番号・列番号
#df.iloc[0, 0] ⇒ 行位置・列位置
#df.loc[行ラベル, 列ラベル] ⇒ ラベル名でのアクセス
cosine_similarity([df2.iloc[0]], [df2.iloc[1]])
#df2の0行目とdf2の1行目をcosineの類似度で

array([[0.16693098]])

In [7]:
#空のリストを作る
cos_list = []


for user_id in df2.index:
    #index名:2/column名:2以降と指定したuser_idの評価2以上のもののcosine類似度を算出して、cos_listに追加(append)
    cos_list.append(cosine_similarity([df2.loc[2, 2:]], [df2.loc[user_id, 2:]]))
cos_list

[array([[0.15834506]]),
 array([[1.]]),
 array([[0.11156787]]),
 array([[0.17969404]]),
 array([[0.06123455]]),
 array([[0.23894671]]),
 array([[0.10827612]]),
 array([[0.10425672]]),
 array([[0.16246959]]),
 array([[0.15239262]]),
 array([[0.13039886]]),
 array([[0.12233863]]),
 array([[0.2211191]]),
 array([[0.22876043]]),
 array([[0.45547941]]),
 array([[0.11430938]]),
 array([[0.20005843]]),
 array([[0.17121885]]),
 array([[0.10226895]]),
 array([[0.04397371]]),
 array([[0.19105808]]),
 array([[0.06501167]]),
 array([[0.13416312]]),
 array([[0.17989739]]),
 array([[0.13282542]]),
 array([[0.43889476]]),
 array([[0.18671165]]),
 array([[0.1033602]]),
 array([[0.17666104]]),
 array([[0.23210951]]),
 array([[0.0825981]]),
 array([[0.2179398]]),
 array([[0.16868044]]),
 array([[0.21436576]]),
 array([[0.07626947]]),
 array([[0.10795673]]),
 array([[0.08052554]]),
 array([[0.0444299]]),
 array([[0.27085974]]),
 array([[0.25381427]]),
 array([[0.10898791]]),
 array([[0.10528266]]),
 arra

In [8]:
#cos_listの数を数えて(len)、順番付けして(range)、ソートする
cos_list1 = sorted(range(len(cos_list)), 
                   #cos_listを基準に、range(len(cos_list))を並び替えたい
                   key=lambda i: cos_list[i], reverse=True)[:51]
cos_list1

[1,
 700,
 930,
 459,
 103,
 130,
 412,
 14,
 833,
 734,
 485,
 25,
 305,
 623,
 767,
 568,
 936,
 742,
 716,
 62,
 462,
 265,
 677,
 519,
 525,
 343,
 128,
 893,
 925,
 295,
 110,
 633,
 438,
 78,
 732,
 276,
 422,
 650,
 443,
 191,
 481,
 918,
 696,
 868,
 859,
 239,
 873,
 156,
 573,
 323,
 935]

In [11]:
#優先度順に並んだcos_listのインデックス番号の順に、df2のインデックス番号をcolumnと
df_similality = df2.iloc[cos_list1[1:]]
df_similality

item_id  1     2     3     4     5     6     7     8     9     10    ...  \
user_id                                                              ...   
701       4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
931       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
460       2.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   3.0   3.0  ...   
104       0.0   0.0   3.0   0.0   0.0   0.0   3.0   0.0   2.0   2.0  ...   
131       4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
413       0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   4.0   0.0  ...   
15        1.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   4.0   0.0  ...   
834       0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   3.0   0.0  ...   
735       4.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   4.0   0.0  ...   
486       4.0   0.0   2.0   0.0   0.0   4.0   5.0   0.0   5.0   4.0  ...   
26        3.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   4.0   0.0  ...   
306       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
624       4.0   0.0   3.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
768       5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
569       4.0   0.0   1.0   0.0   0.0   0.0   4.0   0.0   5.0   0.0  ...   
937       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
743       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
717       0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
63        3.0   0.0   2.0   0.0   0.0   3.0   0.0   0.0   0.0   4.0  ...   
463       1.0   0.0   2.0   0.0   0.0   0.0   4.0   0.0   0.0   1.0  ...   
266       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0  ...   
678       5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
520       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
526       5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
344       3.0   0.0   0.0   4.0   3.0   0.0   4.0   5.0   5.0   0.0  ...   
129       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
894       4.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   4.0   4.0  ...   
926       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
296       5.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0   4.0   2.0  ...   
111       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
634       3.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   5.0   0.0  ...   
439       0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   
79        4.0   0.0   0.0   0.0   0.0   4.0   5.0   0.0   0.0   5.0  ...   
733       2.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   3.0   3.0  ...   
277       4.0   0.0   0.0   0.0   0.0   0.0   2.0   0.0   4.0   0.0  ...   
423       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   4.0  ...   
651       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
444       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
192       0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   5.0   0.0  ...   
482       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
919       4.0   0.0   0.0   1.0   4.0   0.0   3.0   0.0   5.0   0.0  ...   
697       5.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0   4.0   0.0  ...   
869       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
860       0.0   0.0   0.0   4.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
240       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
874       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
157       5.0   0.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
574       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
324       5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   
936       4.0   0.0   4.0   0.0   0.0   5.0   4.0   0.0   4.0   0.0  ...   

item_id  1673  1674  1675  1676  1677  1678  16

In [14]:
df_similality[df_similality[1] != 0.0][1].mean()

np.float64(3.730769230769231)

In [10]:
#類似度の高いユーザーを上位N人抽出
#その人たちが評価していて、自分（user_id=2）が評価してないアイテムを探す
#「その人たちが高評価したアイテム」をレコメンド候補として表示